server:
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081

database:
  driverClass: org.postgresql.Driver
  user: choresbuddy_user
  password: secret
  url: jdbc:postgresql://localhost:5432/choresbuddy
